version: "3.9"
name: projectly_server
services:
  server:
    env_file: .env
    container_name: projectly_server
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 8083:8083
    restart: on-failure
