name: lint
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: backend
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=5m

  lint_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: frontend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint